name: 'Internal GRPC, SQL & BUS API'

on:
  workflow_dispatch:
  push:
    paths:
    - src/InternalGrpcSqlBus.Api/**
    - src/Libraries/proto/_internal-grpc-sql-bus.proto

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/templates/_service-build.yml
    secrets: inherit
    with:
      serviceName: internal-grpc-sql-bus
      servicePath: src/InternalGrpcSqlBus.Api
      hostProjectName: InternalGrpcSqlBus.Api

  deploy:
    strategy:
      matrix:
        environment: [ development, production ]

    needs: build
    uses: ./.github/workflows/templates/_service-deploy.yml
    secrets: inherit
    with:
      service: internal-grpc-sql-bus
      environment: ${{ matrix.environment }}
